<a href="https://colab.research.google.com/github/chris-netizen/Chris---topher/blob/master/Energy_zindi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
<form action="https://api.zindi.africa/v1/competitions/ai-hack-tunisia-4-predictive-analytics-challenge-1/files/train.zip" method="POST"><input type="hidden" name="auth_token" value="JJFLEUicUY2KXz75nSB6Aqzt"><button type="submit" class="Button__base___NhksY Button__blank-normal___1nB5F Data__fileInner___2rJqz"><span class="Button__inner___3jkeF"><div class="Data__filename___VOZWz">train.zip</div><div class="Data__filesize___21c-I">(61.2 MB)</div></span></button></form>

In [ ]:
import requests
import requests, zipfile

url = "https://api.zindi.africa/v1/competitions/ai-hack-tunisia-4-predictive-analytics-challenge-1/files/test.zip"
myobj = {'auth_token' : 'JJFLEUicUY2KXz75nSB6Aqzt'}
x = requests.post(url,data = myobj,stream = True)
target_path = 'data.zip'

handle = open(target_path, 'wb')
for chunk in x.iter_content(chunk_size = 512):
  if chunk:
    handle.write(chunk)
handle.close()

!unzip -qq /content/data.zip

In [ ]:
import requests
import requests, zipfile

url = "https://api.zindi.africa/v1/competitions/ai-hack-tunisia-4-predictive-analytics-challenge-1/files/train.zip"
myobj = {'auth_token' : 'JJFLEUicUY2KXz75nSB6Aqzt'}
x = requests.post(url,data = myobj,stream = True)
target_path = 'datas.zip'

handle = open(target_path, 'wb')
for chunk in x.iter_content(chunk_size = 512):
  if chunk:
    handle.write(chunk)
handle.close()

!unzip -qq /content/datas.zip

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
invoice_train = pd.read_csv('invoice_train.csv')
invoice_test = pd.read_csv('invoice_test.csv')
client_train = pd.read_csv('client_train.csv')
client_test = pd.read_csv('client_test.csv')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [ ]:
print(('Invoice train',invoice_train.shape),('Invoice test',invoice_test.shape))
print(('Client train',client_train.shape),('Client test',client_test.shape))

('Invoice train', (4476749, 16)) ('Invoice test', (1939730, 16))
('Client train', (135493, 6)) ('Client test', (58069, 5))

In [ ]:
#trainset = client_train.merge(invoice_train,how = 'left',on = 'client_id')
#testset = client_test.merge(invoice_test,how = 'left',on = 'client_id')

In [ ]:
#trainset['valid_days'] = ((trainset['invoice_date'] - trainset['creation_date'])/np.timedelta64(1,'D'))
#testset['valid_days'] = ((testset['invoice_date'] - testset['creation_date'])/np.timedelta64(1,'D'))

In [ ]:
client_train['creation_date'] = pd.to_datetime(client_train['creation_date'])
client_test['creation_date'] = pd.to_datetime(client_test['creation_date'])

client_train['cday'] = client_train['creation_date'].apply(lambda x : x.day)
client_train['cmonth'] = client_train['creation_date'].apply(lambda x : x.month)
client_train['cyear'] = client_train['creation_date'].apply(lambda x : x.year)

client_test['cday'] = client_test['creation_date'].apply(lambda x : x.day)
client_test['cmonth'] = client_test['creation_date'].apply(lambda x : x.month)
client_test['cyear'] = client_test['creation_date'].apply(lambda x : x.year)

In [ ]:
client_train.drop('creation_date',axis = 1,inplace = True)
client_test.drop('creation_date',axis = 1,inplace = True)

In [ ]:
invoice_train.head()

        client_id invoice_date  ...  months_number  counter_type
0  train_Client_0   2014-03-24  ...              4          ELEC
1  train_Client_0   2013-03-29  ...              4          ELEC
2  train_Client_0   2015-03-23  ...              4          ELEC
3  train_Client_0   2015-07-13  ...              4          ELEC
4  train_Client_0   2016-11-17  ...             12          ELEC

[5 rows x 16 columns]

In [ ]:
invoice_train['counter_statue'] = invoice_train['counter_statue'].replace('A',10)

In [ ]:
invoice_train['counter_type'].value_counts()

ELEC    3079406
GAZ     1397343
Name: counter_type, dtype: int64

In [ ]:
invoice_train['counter_statue'] = invoice_train['counter_statue'].astype('int')
invoice_test['counter_statue'] = invoice_test['counter_statue'].astype('int')

In [ ]:
invoice_train['counter_type'] = invoice_train['counter_type'].map({'ELEC':1,'GAZ':2})
invoice_test['counter_type'] = invoice_test['counter_type'].map({'ELEC':1,'GAZ':2})

In [ ]:
invoice_train['tcomsommation'] = invoice_train['consommation_level_1'] + invoice_train['consommation_level_2'] + invoice_train['consommation_level_3'] + invoice_train['consommation_level_4']
invoice_test['tcomsommation'] = invoice_test['consommation_level_1'] + invoice_test['consommation_level_2'] + invoice_test['consommation_level_3'] + invoice_test['consommation_level_4']

In [ ]:
invoice_train.drop(['consommation_level_1','consommation_level_2','consommation_level_3','consommation_level_4'],axis = 1,inplace = True)
invoice_test.drop(['consommation_level_1','consommation_level_2','consommation_level_3','consommation_level_4'],axis = 1,inplace = True)

In [ ]:
invoice_train['invoice_date'] = pd.to_datetime(invoice_train['invoice_date'])
invoice_test['invoice_date'] = pd.to_datetime(invoice_test['invoice_date'])

invoice_train['iday'] = invoice_train['invoice_date'].apply(lambda x : x.day)
invoice_train['imonth'] = invoice_train['invoice_date'].apply(lambda x : x.month)
invoice_train['iyear'] = invoice_train['invoice_date'].apply(lambda x : x.year)

invoice_test['iday'] = invoice_test['invoice_date'].apply(lambda x : x.day)
invoice_test['imonth'] = invoice_test['invoice_date'].apply(lambda x : x.month)
invoice_test['iyear'] = invoice_test['invoice_date'].apply(lambda x : x.year)

In [ ]:
invoice_train.drop('invoice_date',axis = 1,inplace = True)
invoice_test.drop('invoice_date',axis = 1,inplace = True)

In [ ]:
invoice_traingrpby = invoice_train.groupby('client_id').mean()
invoice_testgrpby = invoice_test.groupby('client_id').mean()

In [ ]:
invoice_traingrpby = invoice_traingrpby.reset_index()
invoice_testgrpby = invoice_testgrpby.reset_index()

In [ ]:
candi_train = pd.merge(invoice_traingrpby,client_train,on = 'client_id',how = 'outer')
candi_test = pd.merge(invoice_testgrpby,client_test,on = 'client_id',how = 'outer')

In [ ]:
candi_train['value_day'] = abs(candi_train['iday'] - candi_train['cday'])
candi_train['value_month'] = abs(candi_train['imonth'] - candi_train['cmonth'])
candi_train['value_year'] = abs(candi_train['iyear'] - candi_train['cyear'])

candi_test['value_day'] = abs(candi_test['iday'] - candi_test['cday'])
candi_test['value_month'] = abs(candi_test['imonth'] - candi_test['cmonth'])
candi_test['value_year'] = abs(candi_test['iyear'] - candi_test['cyear'])

In [ ]:
candi_train['tcoef'] = candi_train['tarif_type'] / candi_train['counter_coefficient']
candi_train['tread'] = candi_train['tarif_type'] / candi_train['reading_remarque']
candi_train['ttype'] = candi_train['tarif_type'] / candi_train['counter_type']
candi_train['concli'] = candi_train['tcomsommation'] / candi_train['client_catg']
candi_train['tcli'] = candi_train['tarif_type'] / candi_train['client_catg']
candi_train['indiff'] = abs(candi_train['new_index'] - candi_train['old_index'])

candi_test['tcoef'] = candi_test['tarif_type'] / candi_test['counter_coefficient']
candi_test['tread'] = candi_test['tarif_type'] / candi_test['reading_remarque']
candi_test['ttype'] = candi_test['tarif_type'] / candi_test['counter_type']
candi_test['concli'] = candi_test['tcomsommation'] / candi_test['client_catg']
candi_test['tcli'] = candi_test['tarif_type'] / candi_test['client_catg']
candi_test['indiff'] = abs(candi_test['new_index'] - candi_test['old_index'])

In [ ]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
corr = candi_train.corr()
corr.abs()

,tarif_type,counter_number,counter_statue,counter_code,reading_remarque,counter_coefficient,old_index,new_index,months_number,counter_type,tcomsommation,iday,imonth,iyear,disrict,client_catg,region,target,cday,cmonth,cyear,value_day,value_month,value_year,tcoef,tread,ttype,concli,tcli,indiff
tarif_type,1.000000,0.147802,0.002374,0.625390,0.015120,0.006118,0.050776,0.052514,0.018767,0.995818,0.095235,0.034202,0.023232,0.092891,0.150600,0.013977,0.112253,0.054411,0.005001,0.015431,0.017553,0.000156,0.016973,0.070088,0.999777,0.963754,0.989035,0.098889,0.975679,0.027612
counter_number,0.147802,1.000000,0.000512,0.040217,0.079059,0.001381,0.084099,0.083078,0.001905,0.148446,0.020050,0.008787,0.019831,0.210224,0.016110,0.007702,0.048258,0.018917,0.022186,0.029560,0.226908,0.002312,0.024683,0.168546,0.147692,0.163100,0.148116,0.021978,0.142955,0.009769
counter_statue,0.002374,0.000512,1.000000,0.005689,0.353381,0.060954,0.001459,0.001408,0.000755,0.002390,0.001189,0.005371,0.007439,0.009112,0.002843,0.000314,0.002749,0.000665,0.000786,0.002926,0.004737,0.001048,0.007398,0.001051,0.005916,0.006220,0.002376,0.001316,0.002270,0.000106
counter_code,0.625390,0.040217,0.005689,1.000000,0.041611,0.021782,0.246183,0.254342,0.004001,0.637936,0.301020,0.053901,0.039669,0.032517,0.015823,0.175577,0.050822,0.028985,0.016160,0.008000,0.100936,0.017576,0.036281,0.140846,0.625918,0.617528,0.602278,0.287799,0.640295,0.132537
reading_remarque,0.015120,0.079059,0.353381,0.041611,1.000000,0.073365,0.004642,0.000700,0.004213,0.013501,0.060076,0.031924,0.017448,0.352796,0.043687,0.042179,0.014721,0.010962,0.041390,0.025036,0.313978,0.009466,0.000825,0.200867,0.020199,0.158792,0.016271,0.056819,0.022509,0.030098
counter_coefficient,0.006118,0.001381,0.060954,0.021782,0.073365,1.000000,0.004173,0.004184,0.001115,0.006189,0.079484,0.003915,0.007946,0.005540,0.005919,0.036562,0.001648,0.001820,0.000146,0.005635,0.004846,0.006613,0.008144,0.003051,0.016859,0.006797,0.006115,0.072666,0.010949,0.001325
old_index,0.050776,0.084099,0.001459,0.246183,0.004642,0.004173,1.000000,0.992700,0.000672,0.058521,0.414057,0.067476,0.100390,0.023142,0.041799,0.351935,0.081090,0.040202,0.000856,0.002732,0.170328,0.014830,0.017145,0.196901,0.051705,0.049832,0.043737,0.309428,0.117357,0.189940
new_index,0.052514,0.083078,0.001408,0.254342,0.000700,0.004184,0.992700,1.000000,0.098696,0.060562,0.450081,0.069713,0.102980,0.021188,0.041354,0.360987,0.082887,0.040142,0.000606,0.003324,0.163089,0.015365,0.018990,0.189039,0.053454,0.053035,0.045994,0.342559,0.121620,0.262620
months_number,0.018767,0.001905,0.000755,0.004001,0.004213,0.001115,0.000672,0.098696,1.000000,0.014729,0.033041,0.011466,0.017776,0.001565,0.006705,0.066301,0.002369,0.000881,0.001596,0.003198,0.004819,0.001787,0.009210,0.005095,0.018517,0.015316,0.014609,0.019751,0.005839,0.807627
counter_type,0.995818,0.148446,0.002390,0.637936,0.013501,0.006189,0.058521,0.060562,0.014729,1.000000,0.098590,0.033292,0.019969,0.095909,0.149229,0.019394,0.115491,0.053799,0.004784,0.015567,0.015746,0.000793,0.017476,0.069448,0.995612,0.958394,0.974924,0.101768,0.973438,0.032207
tcomsommation,0.095235,0.020050,0.001189,0.301020,0.060076,0.079484,0.414057,0.450081,0.033041,0.098590,1.000000,0.049238,0.070556,0.004582,0.003653,0.231974,0.081641,0.019481,0.000590,0.006300,0.036428,0.011894,0.029729,0.042303,0.097645,0.114450,0.092979,0.910119,0.132703,0.425128
iday,0.034202,0.008787,0.005371,0.053901,0.031924,0.003915,0.067476,0.069713,0.011466,0.033292,0.049238,1.000000,0.122510,0.042399,0.089489,0.131565,0.087916,0.020637,0.015046,0.002163,0.060581,0.147968,0.002102,0.052175,0.034068,0.017022,0.033835,0.024095,0.007788,0.027238
imonth,0.023232,0.019831,0.007439,0.039669,0.017448,0.007946,0.100390,0.102980,0.017776,0.019969,0.070556,0.122510,1.000000,0.025312,0.019027,0.176333,0.062211,0.015813,0.005285,0.002403,0.039500,0.017005,0.138816,0.035237,0.022952,0.017427,0.025480,0.037757,0.011763,0.041905
iyear,0.092891,0.210224,0.009112,0.032517,0.352796,0.005540,0.023142,0.021188,0.001565,0.095909,0.004582,0.042399,0.025312,1.000000,0.089252,0.040472,0.050983,0.034759,0.060776,0.046512,0.607156,0.027628,0.009635,0.222336,0.093085,0.055316,0.091666,0.005616,0.084328,0.002073
disrict,0.150600,0.016110,0.002843,0.015823,0.043687,0.005919,0.041799,0.041354,0.006705,0.149229,0.003653,0.089489,0.019027,0.089252,1.000000,0.032836,0.313309,0.050749,0.013777,0.020293,0.136641,0.003238,0.001590,0.121013,0.150817,0.118588,0.153223,0.012477,0.141328,0.003405
client_catg,0.013977,0.007702,0.000314,0.175577,0.042179,0.036562,0.351935,0.360987,0.066301,0.019394,0.231974,0.131565,0.176333,0.040472,0.032836,1.000000,0.041427,0.054745,0.003059,0.010913,0.054041,0.037738,0.035793,0.045157,0.015199,0.030407,0.011831,0.018076,0.211623,0.144809
region,0.112253,0.048258,0.002749,0.050822,0.014721,0.001648,0.081090,0.082887,0.002369,0.115491,0.081641,0.087916,0.062211,0.050983,0.313309,0.041427,1.000000,0.010940,0.062677,0.015538,0.005410,0.003192,0.010838,0.033285,0.112078,0.109474,0.099936,0.080910,0.102586,0.036453
target,0.054411,0.018917,0.000665,0.028985,0.010962,0.001820,0.040202,0.040142,0.000881,0.053799,0.019481,0.020637,0.015813,0.034759,0.050749,0.054745,0.010940,1.000000,0.006551,0.001626,0.052094,0.001044,0.007243,0.082087,0.054463,0.043112,0.057564,0.015553,0.040575,0.008680
cday,0.005001,0.022186,0.000786,0.016160,0.041390,0.000146,0.000856,0.000606,0.001596,0.004784,0.000590,0.015046,0.005285,0.060776,0.013777,0.003059,0.062677,0.006551,1.000000,0.054963,0.081470,0.251511,0.067270,0.068200,0.004994,0.022174,0.006220,0.000620,0.005674,0.001243
cmonth,0.015431,0.029560,0.002926,0.008000,0.025036,0.005635,0.002732,0.003324,0.003198,0.015567,0.006300,0.002163,0.002403,0.046512,0.020293,0.010913,0.015538,0.001626,0.054963,1.000000,0.084888,0.031590,0.260412,0.079850,0.015351,0.026076,0.015503,0.010903,0.017098,0.002994
cyear,0.017553,0.226908,0.004737,0.100936,0.313978,0.004846,0.170328,0.163089,0.004819,0.015746,0.036428,0.060581,0.039500,0.607156,0.136641,0.054041,0.005410,0.052094,0.081470,0.084888,1.000000,0.017748,0.006367,0.909687,0.017453,0.143216,0.029356,0.025799,0.026098,0.023118
value_day,0.000156,0.002312,0.001048,0.017576,0.009466,0.006613,0.014830,0.015365,0.001787,0.000793,0.011894,0.147968,0.017005,0.027628,0.003238,0.037738,0.003192,0.001044,0.251511,0.031590,0.017748,1.000000,0.021795,0.036218,0.000073,0.006129,0.000951,0.004046,0.007519,0.004253
value_month,0.016973,0.024683,0.007398,0.036281,0.000825,0.008144,0.017145,0.018990,0.009210,0.017476,0.029729,0.002102,0.138816,0.009635,0.001590,0.035793,0.010838,0.007243,0.067270,0.260412,0.006367,0.021795,1.000000,0.012848,0.017117,0.015888,0.017191,0.026490,0.024157,0.018900
value_year,0.070088,0.168546,0.001051,0.140846,0.200867,0.003051,0.196901,0.189039,0.005095,0.069448,0.042303,0.052175,0.035237,0.222336,0.121013,0.045157,0.033285,0.082087,0.068200,0.079850,0.909687,0.036218,0.012848,1.000000,0.070067,0.146817,0.083930,0.034592,0.076097,0.027283
tcoef,0.999777,0.147692,0.005916,0.625918,0.020199,0.016859,0.051705,0.053454,0.018517,0.995612,0.097645,0.034068,0.022952,0.093085,0.150817,0.015199,0.112078,0.054463,0.004994,0.015351,0.017453,0.000073,0.017117,0.070067,1.000000,0.963685,0.988814,0.100433,0.975685,0.027948
tread,0.963754,0.163100,0.006220,0.617528,0.158792,0.006797,0.049832,0.053035,0.015316,0.958394,0.114450,0.017022,0.017427,0.055316,0.118588,0.030407,0.109474,0.043112,0.022174,0.026076,0.143216,0.006129,0.015888,0.146817,0.963685,1.000000,0.952437,0.117275,0.944126,0.038902
ttype,0.989035,0.148116,0.002376,0.602278,0.016271,0.006115,0.043737,0.045994,0.014609,0.974924,0.092979,0.033835,0.025480,0.091666,0.153223,0.011831,0.099936,0.057564,0.006220,0.015503,0.029356,0.000951,0.017191,0.083930,0.988814,0.952437,1.000000,0.096566,0.964608,0.029861
concli,0.098889,0.021978,0.001316,0.287799,0.056819,0.072666,0.309428,0.342559,0.019751,0.101768,0.910119,0.024095,0.037757,0.005616,0.012477,0.018076,0.080910,0.015553,0.000620,0.010903,0.025799,0.004046,0.026490,0.034592,0.100433,0.117275,0.096566,1.000000,0.099619,0.385052
tcli,0.975679,0.142955,0.002270,0.640295,0.022509,0.010949,0.117357,0.121620,0.005839,0.973438,0.132703,0.007788,0.011763,0.084328,0.141328,0.211623,0.102586,0.040575,0.005674,0.017098,0.026098,0.007519,0.024157,0.076097,0.975685,0.944126,0.964608,0.099619,1.000000,0.061882
indiff,0.027612,0.009769,0.000106,0.132537,0.030098,0.001325,0.189940,0.262620,0.807627,0.032207,0.425128,0.027238,0.041905,0.002073,0.003405,0.144809,0.036453,0.008680,0.001243,0.002994,0.023118,0.004253,0.018900,0.027283,0.027948,0.038902,0.029861,0.385052,0.061882,1.000000

In [ ]:
X = candi_train.drop(['target','client_id','counter_statue','months_number','counter_coefficient','cday','cmonth','value_day','value_month','tcoef','indiff'],axis = 1)
y = candi_train['target']

In [ ]:
X.head()

,tarif_type,counter_number,counter_code,reading_remarque,old_index,new_index,counter_type,tcomsommation,iday,imonth,iyear,disrict,client_catg,region,cyear,value_year,tread,ttype,concli,tcli
0,11.0,1335667.0,203.685714,6.971429,9444.542857,9807.514286,1.0,362.971429,21.228571,6.685714,2011.142857,60,11,101,1994,17.142857,1.577869,11.0,32.997403,1.0
1,11.0,678902.0,203.000000,7.216216,14330.756757,14888.297297,1.0,557.540541,14.594595,5.135135,2011.837838,69,11,107,2002,9.837838,1.524345,11.0,50.685504,1.0
2,11.0,572765.0,203.222222,7.055556,32873.000000,33709.500000,1.0,836.500000,12.333333,6.611111,2010.944444,62,11,301,1986,24.944444,1.559055,11.0,76.045455,1.0
3,11.0,2078.0,413.000000,6.150000,94.150000,95.350000,1.0,1.200000,16.350000,5.550000,2008.600000,69,11,105,1996,12.600000,1.788618,11.0,0.109091,1.0
4,11.0,19575.0,207.000000,8.857143,6900.428571,7823.071429,1.0,922.642857,8.071429,7.571429,2016.857143,62,11,303,2014,2.857143,1.241935,11.0,83.876623,1.0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test  = train_test_split(X,y, test_size = 0.25,random_state = 101)

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rfc = RandomForestClassifier(n_estimators=3500,max_depth=4,min_samples_split=12,max_leaf_nodes=23)

In [ ]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=4, max_features='auto',
                       max_leaf_nodes=23, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=12,
                       min_weight_fraction_leaf=0.0, n_estimators=3500,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
preds = rfc.predict(X_test)
probs = rfc.predict_proba(X_test)[:,1]

In [ ]:
probs

array([0.04462225, 0.04065213, 0.06303174, ..., 0.00579773, 0.07183592,
       0.06730276])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
error = 1 - accuracy_score(y_test,preds)
error

0.05479128535159705

In [ ]:
from sklearn.metrics import roc_auc_score

In [ ]:
_auc = roc_auc_score(y_test,probs)

In [ ]:
print(_auc)

0.7930150769852519

In [ ]:
test = candi_test.drop(['client_id','counter_statue','months_number','counter_coefficient','cday','cmonth','value_day','value_month','tcoef','indiff'],axis=1)

In [ ]:
test_prob = rfc.predict_proba(test)[:,1]

In [ ]:
ss = pd.read_csv('SampleSubmission (1).csv')

In [ ]:
ss.head()

          client_id    target
0     test_Client_0  0.957281
1     test_Client_1  0.996425
2    test_Client_10  0.612359
3   test_Client_100  0.776933
4  test_Client_1000  0.571046

In [ ]:
ss.target = test_prob

In [ ]:
ss.head()

          client_id    target
0     test_Client_0  0.062454
1     test_Client_1  0.080029
2    test_Client_10  0.066485
3   test_Client_100  0.029580
4  test_Client_1000  0.067801

In [ ]:
ss.to_csv('5.csv',index=False)